import json
import re
from datetime import date
from typing import Any, Dict, List, Optional

from openai import AsyncOpenAI
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.backtest import BacktestRun
from app.models.strategy import Strategy
from app.models.user import User


JSON_OBJECT_PATTERN = re.compile(r"\{(?:[^{}]|\{[^{}]*\})*\}", re.S)


def create_strategy(db: Session, user_id: int, name: str, description: Optional[str], rules_json: Dict[str, Any]) -> Strategy:
    strategy = Strategy(
        user_id=user_id,
        name=name,
        description=description,
        rules_json=json.dumps(rules_json),
    )
    db.add(strategy)
    db.commit()
    db.refresh(strategy)
    return strategy


def get_user_strategies(db: Session, user_id: int) -> List[Strategy]:
    return db.query(Strategy).filter(Strategy.user_id == user_id).order_by(Strategy.created_at.desc()).all()


def get_strategy(db: Session, user_id: int, strategy_id: int) -> Optional[Strategy]:
    return db.query(Strategy).filter(Strategy.user_id == user_id, Strategy.id == strategy_id).first()


def save_backtest_run(
    db: Session,
    strategy_id: int,
    ticker: str,
    start_date: str,
    end_date: str,
    results: Dict[str, Any],
) -> BacktestRun:
    backtest = BacktestRun(
        strategy_id=strategy_id,
        ticker=ticker.upper(),
        start_date=start_date,
        end_date=end_date,
        results_json=json.dumps(results),
    )
    db.add(backtest)
    db.commit()
    db.refresh(backtest)
    return backtest


def get_backtest_run(db: Session, user_id: int, run_id: int) -> Optional[BacktestRun]:
    return (
        db.query(BacktestRun)
        .join(Strategy, Strategy.id == BacktestRun.strategy_id)
        .filter(Strategy.user_id == user_id, BacktestRun.id == run_id)
        .first()
    )


def run_backtest(db: Session, user_id: int, strategy_id: int, ticker: str, start_date: date, end_date: date) -> BacktestRun:
    from app.backtesting.engine import BacktestEngine

    strategy = get_strategy(db, user_id, strategy_id)
    if not strategy:
        raise ValueError("Strategy not found or access denied.")

    engine = BacktestEngine()
    results = engine.run(
        rules_json=json.loads(strategy.rules_json),
        ticker=ticker,
        start_date=start_date.isoformat(),
        end_date=end_date.isoformat(),
    )

    return save_backtest_run(db, strategy_id, ticker, start_date.isoformat(), end_date.isoformat(), results)


async def generate_ai_strategy(db: Session, user: User, prompt: str) -> Dict[str, Any]:
    if not settings.OPENAI_API_KEY:
        raise ValueError("OPENAI_API_KEY is not configured.")

    client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY)

    system_prompt = (
        "You are a quantitative trading strategist. Respond with a single JSON object only, no additional text. "
        "The JSON object must include: name, description, risk_profile, reasoning, rules_json. "
        "rules_json must contain entry and exit arrays. Each rule item must include indicator, operator, and value. "
        "Supported indicators: RSI, MACD, SMA, EMA, Bollinger Bands, ATR, Volume. "
        "Use the prompt exactly and generate a practical tradable rule set for a single equity ticker if the user mentions one. "
    )

    user_prompt = (
        f"Generate a trading strategy from the following user request: {prompt}. "
        "Return indicator rules in a valid JSON structure only."
    )

    response = await client.chat.completions.create(
        model=settings.OPENAI_MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0.2,
        max_tokens=500,
    )

    content = response.choices[0].message["content"].strip()
    match = JSON_OBJECT_PATTERN.search(content)
    if not match:
        raise ValueError("Unable to parse strategy JSON from AI response.")

    strategy_data = json.loads(match.group(0))

    if "rules_json" not in strategy_data or not isinstance(strategy_data["rules_json"], dict):
        raise ValueError("AI response did not include valid rules_json.")

    strategy = create_strategy(
        db=db,
        user_id=user.id,
        name=strategy_data.get("name", "AI Generated Strategy"),
        description=strategy_data.get("description", "Generated by AI Analyst."),
        rules_json=strategy_data["rules_json"],
    )

    return {
        "id": strategy.id,
        "user_id": strategy.user_id,
        "name": strategy.name,
        "description": strategy.description,
        "rules_json": json.loads(strategy.rules_json),
        "risk_profile": strategy_data.get("risk_profile"),
        "reasoning": strategy_data.get("reasoning"),
    }


def optimize_backtest(
    db: Session,
    user_id: int,
    strategy_id: int,
    ticker: str,
    start_date: date,
    end_date: date,
    parameter: str,
    lower_bound: float,
    upper_bound: float,
    step: float = 1.0,
) -> Dict[str, Any]:
    strategy = get_strategy(db, user_id, strategy_id)
    if not strategy:
        raise ValueError("Strategy not found or access denied.")

    from app.backtesting.optimizer import BacktestOptimizer

    optimizer = BacktestOptimizer()
    return optimizer.optimize(
        base_rules=json.loads(strategy.rules_json),
        parameter=parameter,
        lower_bound=lower_bound,
        upper_bound=upper_bound,
        step=step,
        ticker=ticker,
        start_date=start_date.isoformat(),
        end_date=end_date.isoformat(),
    )
